### ISSUE TITLE
Get the lib again compilable as part of NixOS/nixpkgs

### ISSUE THREAD

**Issue by Mikolaj** [LambdaHack/LambdaHack#103]
@peti: if I'm badgering you too much, just let me know, otherwise, please help me out :)

in file hackage-packages.nix

* under "sdl2-ttf", could `hydraPlatforms` be extended to Linux? it works for me when compiled manually via cabal

* could "LambdaHack" (and "Allure") be enabled again? there is a chance the new version compiles now --- am I expected to install nixpkgs, try myself and issue a PR?

Thanks a lot!

**Comment by peti** [comment]
I've made the necessary changes in https://github.com/peti/nixpkgs/commit/4710fae5600e007460be2036f103075f4c833413 and https://github.com/peti/nixpkgs/commit/11a57942437d1de6c9b05ecb63ac19dc8c8b92be. They'll hit the `master` branch in a day or two. Thank you very much for the heads-up.

**Comment by Mikolaj** [comment]
Thank you. It all works now. Closing.
