### ISSUE TITLE
Add `stack` support

### ISSUE THREAD

**Issue by vrom911** [LambdaHack/LambdaHack#107]
It would be really great to add `stack.yaml` which will allow to build project with `stack`.

**Comment by Mikolaj** [comment]
Indeed, that should be very easy to do. Also `cabal.project` for `cabal new-build`. Any volunteers?

**Comment by Mikolaj** [comment]
Perfect. Thank you.

**Comment by Mikolaj** [comment]
`cabal new-build` doesn't yet support `--datadir`, so until it's implemented, some workaround needs to be applied in order to use `new-build` (install the font using normal `cabal install` or compile with exported `LambdaHack_datadir=.` environment variable). Tough luck. Closing.
