### ISSUE TITLE
Find a better name for "temporary condition"

### ISSUE THREAD

**Issue by Mikolaj** [LambdaHack/LambdaHack#131]
These are "poisoned", "hasted", etc., pseudo-organs seen in the organ menu and temporary condition lore screens. The name is too long, unnatural and probably not very clear, but I'm not a native speaker, so I'm not sure.

"Status"? But then I'd need to change PLAYING.md not to call the bottom line the status line, since it doesn't display any temporary conditions.

"Affliction" is negative and conditions can be positive.

"Standing"? But plural sounds funny. Perhaps singular for the whole list of them? But then a single one would be "component of standing"?

"Kilter"? "Fitness"? "Constitution"? "Disposition"? "Form"? It needs to suggest the "temporary" aspect and at least of the these probably don't.

**Comment by Peritract** [comment]
What's wrong with "conditions"? It has the connotation of "temporary" already.

**Comment by Mikolaj** [comment]
OK, let's try. Before:

![dashboard](https://user-images.githubusercontent.com/281893/38646762-9073a9a0-3de9-11e8-9f55-d53556570032.png)

After:

![lore](https://user-images.githubusercontent.com/281893/38646768-964cb2f4-3de9-11e8-9783-be61b3cbea18.png)

**Comment by Mikolaj** [comment]
What do you think?

**Comment by tr00per** [comment]
In MMOs they're usually called "buffs" and "debuffs" by players.
Wikipedia calls them "status effects" - https://en.wikipedia.org/wiki/Status_effect ;)

**Comment by Mikolaj** [comment]
Wow, a Wikipedia page. Who would have thought. Thank you.

"Buffs" is short and understandable, but I need a term that encompasses the negative ones as well and "(de)buffs" is messy.

"Status" is indeed an option ("effect" makes it too long and more jargon-like, IMHO), but "condition" is probably more precise.

**Comment by Mikolaj** [comment]
OK, let it be "conditions". Thank you for your input!

TODO: at the next AI rewrite, rename AI.Condition do AI.Predicate and similarly each individual function to avoid confusion.

Renamed on master branch. Closing.
