### ISSUE TITLE
Make LambdaHack and Allure available on Homebrew

### ISSUE THREAD

**Issue by PabloReszczynski** [LambdaHack/LambdaHack#142]
I have literally no idea how to do this, but I will work on figuring it out.

**Comment by Mikolaj** [comment]
Everybody starts at "no idea". :) If you'd like to think aloud here, in this issue, or just note down questions, progress, things that you don't want to forget, etc., I'd be interested to read that. Have fun!

**Comment by PabloReszczynski** [comment]
Apparently all that is needed is to add a Formula directory on the repo with a ruby script with the install instructions. Then osx users can `brew tap AllureOfTheStars && brew install Allure`

**Comment by PabloReszczynski** [comment]
More [](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and [here](https://brew.sh/)

**Comment by Mikolaj** [comment]
Fantastic. So, would you propose we add homebrew-allure repo under the AllureOfTheStars organization or rather a Formula directory to the existing Allure repo? In either case your organizatino-wide write access should be enough to do that.

I didn't quite grasp: would the formula install already compiled binaries (e.g., from `latest/` release) or compile development version (or a tag?) from scratch? Ideally, we do that in a way that we never have to touch it (e.g., after each release).

**Comment by PabloReszczynski** [comment]
The formula installs compiled binaries.
I think a separate repo would be better to experiment first.

**Comment by Mikolaj** [comment]
Go for it!

**Comment by Mikolaj** [comment]
I've created the repo at https://github.com/AllureOfTheStars/homebrew-allure
No pressure though, we are having fun and benefiting the world at large only as a side-effect. :)

**Comment by Mikolaj** [comment]
We now have Travis CI compilation and test run on OS X. See, e.g., https://travis-ci.org/AllureOfTheStars/Allure/jobs/424127920

With some more effort, we can pack a binary in the CI run and export it, e.g., as done here: https://github.com/haskell/ThreadScope/blob/master/.travis.yml#L115 

If we could then make it available as a Homebrew package, that would make the whole process (except for manual testing before major releases) fully automatic. That would be amazingly perfect.

**Comment by Mikolaj** [comment]
I've just applied to add Allure to Homebrew-core: https://github.com/Homebrew/homebrew-core/pull/39142

Please somebody test it locally (I just rely on CI).

**Comment by Mikolaj** [comment]
Done. Closing. Run `brew install allureofthestars` to get binaries from this formula: https://formulae.brew.sh/formula/allureofthestars
