### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by phadej** [LambdaHack/LambdaHack#175]
```
engine-src/Game/LambdaHack/Client/UI/Frontend/Dom.hs:174:60: error:
    • Couldn't match expected type ‘K.PointUI’ with actual type ‘Point’
```

Some version bound is missing?

**Comment by Mikolaj** [comment]
No, just between-releases bitrot (last tag should compile fine). Let me attempt compilation and fix...

**Comment by Mikolaj** [comment]
Recompilation of deps takes forever, so I've just blindly attempted a hotfix. Please try. :)

**Comment by Mikolaj** [comment]
Oh, and sadly you need to do

    cp LambdaHack.cabal.flattened LambdaHack.cabal

because cabal with ghcjs don't yet handle internal libraries. But then it should compile. I does for me.

**Comment by phadej** [comment]
This works, thanks!
