### ISSUE TITLE
What is the preferred Development Environment (IDE/Editor)?

### ISSUE THREAD

**Issue by EHotwagner** [LambdaHack/LambdaHack#191]
I got a working VSCode +HIE installation on Ubuntu going but this project hangs during initializion phase: "Initializing Cabal Project". Before spending some more time on the wonderful world of Haskell tooling i wanted to ask: what is everybody using and is working?

**Comment by Mikolaj** [comment]
Hi,

First and foremost, CI is working on Ubuntu, Windows and OS/X. The Ubuntu script is in

https://github.com/LambdaHack/LambdaHack/blob/master/.travis.yml#L291

and the results are at 

https://travis-ci.org/LambdaHack/LambdaHack/builds

Myself, I just use `cabal new-build -j1 .` from the commandline or from emacs with and old haskell-mode, but I know `stack` used to work too. Does the commandline compilation work for you? Does a "Hello World" projects work for you in VSCode +HIE, according to their documentation?

**Comment by EHotwagner** [comment]
Hi,
Compilation does work fine. 
cabal build does the trick after installing pkg-config, libsdl2 and sdl2-ttf.
VSCode + HIE works for simple Hello World projects.

After waiting for some time VSCode gives me now: 
"can't load .so/.DLL for: /home/eugen/.cabal/store/ghc-8.6.5/sdl2-2.5.1.0-[....]-ghc8.6.5.so (libSDL2-2.0.so.0: cannot open shared object file: No such file or directory)"

Some intellisense would be great to help me understand the project structure.  Anyway might give it a try with emacs and old haskell mode.
thx a lot.

**Comment by Mikolaj** [comment]
I'm afraid we don't have any VSCode guru onboard. However, any intellisense (that's a config file, right?) would be welcome, if you ever happen to create one.

Let me know how it goes for you and ask early and often --- docs and tickets are usually very cryptic, written in a lazy way ;), so questions would be a good trigger to expand them.

**Comment by Mikolaj** [comment]
BTW, I don't know if it's in any docs, but putting `optimization: False` in your `cabal.project.local` would speed up compilation by an order of magnitude, and the game would still be fast enough for normal playing.

**Comment by EHotwagner** [comment]
No problem. I am not particularly hung up on VSCode and HIE. https://en.wikipedia.org/wiki/Intelligent_code_completion or intellisense is just editor assistance for autocompletion and type information. VSCode and also some Emacs modes implement this with lsp (language server protocol) which standardizes this across languages. 

Since i am new to the project type information and go to definition.... would be nice.

**Comment by rszczers** [comment]
Hey,

actually, not so long time ago I've managed to get the project working under VSCode with all the bells and whistles, both with hie or ghcide. It works fine under stack with basic `hie.yaml` placed in project directory:

```
cradle:
  stack:
```

Try to build the project with stack beforehand. Also, keep in mind that your HIE has to be compiled with the same GHC version as the project. Try out changing resolver to newer one, if that's the case.

**Comment by EHotwagner** [comment]
Thanks a lot, will give it a try tomorrow and report back.

**Comment by Mikolaj** [comment]
Guys, please feel free to include that `hie.yaml` in the repo, particularly if it works for more than one person. I will include my sample `cabal.project.local` files.

**Comment by EHotwagner** [comment]
I changed my stack.yaml to:
```
resolver: lts-14.23
packages: ['.']
extra-deps: 
- splitmix-0.0.3@sha256:455de9326ae5bbe5492cbb140fefb04cf988501e25b204dabaf755ab67400d9d,4835
flags: {}
extra-package-dbs: []
```

and am now able to build the project with stack. VSCode now also starts with "Initializing Stack project". Sadly I now get:

`The Haskell HIE (LambdaHack) server crashed 5 times in the last 3 minutes. The server will not be restarted.`
From what i read this might hint to a version conflict between HIE ghc and the projects. It seems to me that everything is on 8.6.5 tough. Starting a hie manually in the project folder uses hie-8.6.5 and so does stack. 

I will read up on debugging HIE and take a look.

**Comment by rszczers** [comment]
Most recent `hie` uses `nightly-2020-01-31` resolver by default. That's ghc-8.8.2.

**Comment by Mikolaj** [comment]
BTW, I have no idea if LH works with GHC 8 or 10. Feel free to try and update `tested-with` field of `LambdaHack.cabal`. And extend CI to test also the new GHC.

**Comment by rszczers** [comment]
I've just managed to setup hie on my different machine with ubuntu. I struggled for a while, since vscode didn't even try to run `hie`, but it worked smoothly just after I updated vscode to version 1.42.0.

**Comment by EHotwagner** [comment]
I am busy for 2-3 days but will give it a try afterwards. Maybe it just works out of the box with:
https://github.com/hmemcpy/haskell-hie-devcontainer
https://code.visualstudio.com/docs/remote/containers
That would easiest and a stable target.

**Comment by Mikolaj** [comment]
Hi @EHotwagner, how is it going? No pressure, just a token of appreciation for your kind interest. :)

**Comment by EHotwagner** [comment]
> Hi @EHotwagner, how is it going? No pressure, just a token of appreciation for your kind interest. :)

Ah sorry, had to much work the last days and didnt get around to it. Next 2 weeks should be better. I am going through some docker tutorials before tackling this since it seems like a usefull skill anyway.

**Comment by Mikolaj** [comment]
Wow, cool. Have fun!

**Comment by Mikolaj** [comment]
BTW, LambdaHack does work fine with GHC 8.8 and 8.10, I've just checked in CI.

**Comment by Mikolaj** [comment]
@EHotwagner: ping?

**Comment by EHotwagner** [comment]
Ahh nice. Sorry got cobbled up in different projects and don't have a working Haskell setup right now. I don't think i will get around to test it in the foreseeable future. Feel free to close the issue on my part.

**Comment by Mikolaj** [comment]
OK. You are warmly welcome to visit any time. We are having fun coding stuff, much of it newcomer-friendly, so we'd help you get started and share in the fun as soon as you feel like it.
