### ISSUE TITLE
Test with QuickCheck that in-game macros do the same thing as named macros

### ISSUE THREAD

**Issue by Mikolaj** [LambdaHack/LambdaHack#198]
From #197:

"You mean checking if in-game macro does the same thing as running the same macro as predefined one? This seems valid and we could check this automatically."

"Yes. If we want that property, that's finally a good candidate for QuickCheck. :)"

If during the testing we discover it's not always the case, the restricted range of the test would document how common that is.

**Comment by rszczers** [comment]
How about using [hedgehog](https://hackage.haskell.org/package/hedgehog)?

**Comment by Mikolaj** [comment]
Only in gloves, but otherwise, fine. :)

**Comment by Mikolaj** [comment]
I was forced to enable QuickCheck not HedgeHog, because of doctests. Anyway, it's now available for use in tests on master.
