### ISSUE TITLE
Make Key Bindings for Switching through Teammates more Intuitive for Beginners

### ISSUE THREAD

**Issue by bulbousBullfrog** [LambdaHack/LambdaHack#206]
More specifically after some discussion we came to the following proposal based on what I tried naturally on my first playthrough.
- Swap the existing behavior of Tab with S-Tab. This is because as a beginner I wasn't aware I could switch between teammates on separate floors using the most basic way to change, TAB. If we switch this behavior it will be clear that you can control teammates on other floors.
- Keep the ability to toggle through teammates restricted to a level. This is behavior of TAB currently. To keep this we can swap it to Alt-Tab
- Add the new ability to switch direction while toggling with shift. This is so that with 5 Teammates you wouldn't have to tab through them all to select then one you want. Instead you can tab along, then switch directions of the changing with shift. This is similar to how tab behavior works with tabs in browsers.
- (Optional) Add the new shift behavior restricted to teammates on a level. Here you should be able to switch through teammates, and change the direction of selection with shift, but only for the teammates on the current level. This would be done with the binding Alt+Shift-Tab

**Comment by Mikolaj** [comment]
Indeed this is perhaps the best first issue there is: a ton of baby steps that (usually) make sense intuitively and that compiler warnings and `git grep` would natural lead through. A portion of this would also need to be exactly repeated for Allure.

To make it precise: I think the behaviour of Tab should be that of current S-Tab, but with the opposite direction. So Tab should move 0 1 2 3 and on all levels. Agreed that A-S-Tab makes sense.

**Comment by bulbousBullfrog** [comment]
Was the Human Command for Cycling through all members on all levels called MemberBack because of the 'Shift' key added to Tab? I am asking because I have the behavior I want implemented, but I am not sure if I should change the naming. 

Situation naming situation now:
`Cycling on the level -> MemberBack(A-Tab)`
`Cycling all levels -> MemberCycle(Tab)`

Also, I will probably have to come up with new HumanCommands for the A+S-Tab feature, but I'm waiting to do that until I have the basic functionality of swapping the existing behavior with correct naming

**Comment by Mikolaj** [comment]
Yes, you are right, `MemberBack` is a misnomer caused by the BackTab keybinding and the fact that it has hardwired the behaviour that it cycles backwards (4 3 2 1). But the crucial difference is not cycling backwards, but cycling through teammates in the whole dungeon. Yes, it's a very good idea to rename it. 

Also, obviously the direction of cycling should not be hardwired but based on yet another Bool parameter called, e.g., `forward`. I'd need to look closer, but I think the `reverse` you can find in `memberBack` code should be there only if `forwad` is false. Yes, looks like it, because there is no `reverse` in `memberCycle`.

**Comment by bulbousBullfrog** [comment]
I saw the reverse call in the function, and thought the exact same thing, namely using a Bool passed to it so that it can handle both scenarios. I will put a flag in to determine forward/backward cycle direction. 
For the name, I will come up with something maybe a little more fitting, and once the code is in the repo you can let me know if we should improve it.

**Comment by bulbousBullfrog** [comment]
Feature was implemented including the new optional shift behavior see pull request https://github.com/LambdaHack/LambdaHack/pull/207
