### ISSUE TITLE
Add config (and commandline) option to run in both kinds of fullscreen

### ISSUE THREAD

**Issue by Mikolaj** [LambdaHack/LambdaHack#221]
https://hackage.haskell.org/package/sdl2-2.5.2.0/docs/SDL-Video.html#v:Fullscreen

**Comment by MichaelMackus** [comment]
This is interesting to me. How are you envisioning the implementation? Should we just scale using the same aspect ratio? 

SDL has a "SetLogicalSize" (or similar) method that should handle the scaling for this with relatively little pain.

**Comment by Mikolaj** [comment]
Oh, I didn't know about `SetLogicalSize`. I'd be grateful for a link, particular to haddocks on Hackage.

I lack vision on this one. The brave volunteer, should he accept the challenge, would need to try both fullscreen methods and (try to) come back to tell the tale. I'm ready to be surprised.

If needed, the game can be coarsely scaled using

https://github.com/LambdaHack/LambdaHack/blob/95547fbb0549ba3e32a36911f60e0834f112dd3f/GameDefinition/config.ui.default#L49-L51

The advantage over scaling SDL textures is that it doesn't break font hinting (very important) nor pixel-boundary aware antialiasing (if any and if separate). If really needed, we can turn hinting off completely (see https://github.com/adobe-fonts/source-sans-pro/issues/193#issuecomment-678488830), but currently it causes kerning artifacts with at least some fonts. See also #127. In any case, unless we talk about 4K or games with very little text, either hinting or a dedicated rectangular bitmap font that needs no scaling is needed IMHO. I've heard too many player complaints about tired eyes.

**Comment by MichaelMackus** [comment]
Hmm, I suppose there might be more font scaling issues than I anticipated.

Here is a link to the method I was referring to:
https://hackage.haskell.org/package/sdl2-2.4.1.0/docs/SDL-Video-Renderer.html#v:rendererLogicalSize
- I have used this before in a haskell SDL game and it worked out of the
box with no need to edit any font sizes or pixel values. I simply edited it
to match the unscaled pixel size and set the fullscreen flag for sdl. The
result looked pretty good to me, probably not perfect but it might be a
good first step at least.

**Comment by MichaelMackus** [comment]
Here is a link to the game I was referring to:
https://github.com/MichaelMackus/hsrisk/blob/master/app/Main.hs

**Comment by Mikolaj** [comment]
Oh, great. That's definitely a good first step and a point in the design space we want to fully explore. Go for it. We may later try to match `allFontsScale` instead, either universally or for a few popular screen sizes, take screenshots of longer texts in small font with C-S-P and compare the results.

**Comment by Mikolaj** [comment]
I've merged the PR, added a few more commits and it works great! Thanks go to @MichaelMackus. Closing.
