### ISSUE TITLE
Escape screensaver not running in automatic mode

### ISSUE THREAD

**Issue by MichaelMackus** [LambdaHack/LambdaHack#224]
I'm still working my way around this library, but while doing some experimenting I found that when the "screensaverEscape" mode is triggered on the main menu, it always jumps me into a game and bypasses the automatic AI. Essentially, this screensaver behaves like an actual game mode and jumps me right into the game without letting me configure the mode/settings first. I'm on git SHA 95547fbb0549ba3e32a36911f60e0834f112dd3f using GHC 8.8.3 via stack.

I noticed the following code "fixes" this, but I don't think it is 100% satisfactory since it puts the hero first in the list (contradictory to the comment below it):

```haskell
-- TODO figure out why this change fixes automation
rosterEscapeAlt = Roster
  { rosterList = [  ( playerHero {fhiCondPoly = hiHeroMedium}
                   , [(-7, 1, SCOUT_HERO), (-7, 2, ESCAPIST_HERO)] )
                   ,( playerAntiHero { fname = "Indigo Researcher"
                                    , fcanEscape = False  -- start on escape
                                    , fneverEmpty = False  -- loot after killing
                                    , fhiCondPoly = hiHeroMedium }
                   , [(-7, 1, SCOUT_HERO), (-7, 6, AMBUSHER_HERO)] )

                     -- second on the list to let foes occupy the exit
                 , (playerHorror, []) ]
  , rosterEnemy = [ ("Explorer", "Indigo Researcher")
                  , ("Explorer", "Horror Den")
                  , ("Indigo Researcher", "Horror Den") ]
  , rosterAlly = [] }

**Comment by Mikolaj** [comment]
Not having a link to your branch, where I could examine the context and try to reproduce, I can't say for sure. However, no wonder the switch of factions in the roster defeated the screensaver modification --- it only affects the first element on the roster list:

https://github.com/LambdaHack/LambdaHack/blob/95547fbb0549ba3e32a36911f60e0834f112dd3f/GameDefinition/Content/ModeKind.hs#L421

and the first element on the modified list already has the very AI setup that screensaver adjustment sets.

What is it exactly that you'd like to accomplish and how the results differ from you expectations? You are aware you can toggle AI directly in main menu ("toggle autoplay")? The screensaver modes do almost exactly that.

**Comment by MichaelMackus** [comment]
I meamt the screensaver mode for the "escape" scenario isn't properly
working like the other screensavers (it jumps you into a new game directly
and never starts the automations). This is on an unmodified lambdahack and
occurs in both allure of the stars and the sample game.

**Comment by Mikolaj** [comment]
Ouch, that's good to know. I'm now able to reproduce that by pressing C-q many times. I think that's caused by my renumbering of factions a few weeks ago and the consequent ability to have more than one UI client (but only one active at once, in theory, probably that's where it fails). It even locks up for me.

**Comment by Mikolaj** [comment]
I think I fixed it now for LambdaHack (pushed). Concurrency is hard. However, there is no problem that can't be solved with a judicious use of `unsafePerformIO`.

**Comment by Mikolaj** [comment]
No, I'm wrong, I fixed the locking up, but not what you observed. At it...

**Comment by Mikolaj** [comment]
Really fixed now. I followed your lead and I'm no longer changing only the first faction's AI control, but all that need it (in reality it will only be one, until split-screen multiplayer is re-added to the game).

**Comment by MichaelMackus** [comment]
😱

**Comment by MichaelMackus** [comment]
Nice!

**Comment by MichaelMackus** [comment]
Looks to be working to me now.
