### ISSUE TITLE
Follower AI

### ISSUE THREAD

**Issue by MichaelMackus** [LambdaHack/LambdaHack#225]
I'm not sure if this is directly supported or not, but in one game I am envisioning it would be a perfect if we could just alter the friendly units to follow the player when not being interacted with. I feel this could get complicated since currently the setup is very "tactical" in that each AI move uses 1 turn. Making this toggleable would work for my current game idea - I'm envisioning something where the AI just "auto follows" until the user presses a hotkey (maybe "space") which allows the player to control each AI sequentially like it is now. Pressing the same hotkey (say "space") then reverts the state back to autofollow mode allowing the AI to follow without so much micro-management. We could even go so far as support something where the AI autofollows until a "battle" is detected, and when in battle the AI are all controlled manually.

I kind of see this as a bridge between full tactical squad-based combat and quick maneuverability. Something akin to "Baldur's Gate" and other Black-Isle games, but fully turn-based of course.

**Comment by MichaelMackus** [comment]
After posting this, I realized this probably better belongs in the Wiki. I have made a wiki article with the content [here](https://github.com/LambdaHack/LambdaHack/wiki/Follower-AI). Please let me know if this is supported and/or desired if you find the time.

**Comment by Mikolaj** [comment]
Hi! Thank you for the idea and for the Wiki page. Please experiment with `make frontendSafari`, look at

https://github.com/LambdaHack/LambdaHack/blob/95547fbb0549ba3e32a36911f60e0834f112dd3f/GameDefinition/Content/ModeKindPlayer.hs#L110

and

https://github.com/LambdaHack/LambdaHack/blob/95547fbb0549ba3e32a36911f60e0834f112dd3f/GameDefinition/Content/ModeKindPlayer.hs#L56

ask questions (here or on Discord or matrix or gitter or email  or elsewhere) and maintain the proposal on the wiki as you see fit.

I have an impression your Space-toggled doctrine can be fully implemented even just in game content or, though that would be a debugging nightmare, even in player config file. However, I may be missing something. In particular, probably the player that never toggles the doctrine to one-by-one would always be better off, given competent AI (unless AI melee is forbidden?), so maybe you actually look for something like running together (where actors move one-per-turn, but generalized and automatic, see)

https://github.com/LambdaHack/LambdaHack/blob/95547fbb0549ba3e32a36911f60e0834f112dd3f/GameDefinition/PLAYING.md#L232-L235

Also http://hackage.haskell.org/package/SpacePrivateers by @tuturto uses a similar mode, but it's quite bitrotted ATM, sadly.

**Comment by MichaelMackus** [comment]
Thanks for the reply! I think the method you referred to should be
sufficient for a prototype of the game idea I had! I will have to test this
some more when I have the time.

I will be sure to update the wiki once I do some more research with a more
coherent design strategy.
