### ISSUE TITLE
Create a portable, statically linked AppImage Linux package

### ISSUE THREAD

**Issue by Mikolaj** [LambdaHack/LambdaHack#248]
The game binary already incorporates all data files it needs, including fonts.

With some luck, we could link the game fully statically as at https://github.com/utdemir/ghc-musl and https://github.com/nh2/static-haskell-nix.

Then, if there is any value added in that, it could be packages as AppImage (https://docs.appimage.org/index.html).

Related: Windows binaries could be statically linked as well, perhaps, to avoid distributing all those dlls as separate files.

Edit: see the note at the end of Makefile.

**Comment by Mikolaj** [comment]
An overheard hint about how to create an appImage:

> stack install hsinstall
> hsinstall --mk-appimage packagename
> https://gitlab.com/dpwiz/ld48/-/tree/main/util/resources/appimage
> what's supposed to be in the share/hsinstall directory?
> copy the files from the hsinstall repo to the right directory manually

but I'm no longer sure I'm willing to spend time wrestling with static linking after the ordeal of https://github.com/utdemir/ghc-musl/issues/14

**Comment by Mikolaj** [comment]
Closing until there's is a hardcore volunteer willing to move it forward or until I move from SDL2 to Vulkan or whatever video library permits (easy) static linking.

**Comment by nh2** [comment]
In `static-haskell-nix`,I have succeeded building SDL2 and associated libraries statically now, and also `LambdaHack`, with some overrides I still need to clean up.

But what needs research is how to make a static SDL2 find a graphics card or use software rendering via Mesa `llvmpipe`:

```sh
/nix/store/wydhcgwplw9grms8d3y8sdfm5srg8xgb-LambdaHack-0.10.2.0/bin/LambdaHack
LambdaHack: SDLCallFailed {sdlExceptionCaller = "SDL.Init.init", sdlFunction = "SDL_Init", sdlExceptionError = "No available video device"}
```

https://github.com/nh2/static-haskell-nix/pull/108#issuecomment-897742983
