### ISSUE TITLE
Trying to build & run - cabal reports inconsistencies, stack works after tweaks, but then how do I run?

### ISSUE THREAD

**Issue by JamieFristrom** [LambdaHack/LambdaHack#250]
Hi! 
This looks really cool. I'm trying to learn how to approach game dev more functionally, interested in how you approached it.
But ideally I'd be able to get it to build & run locally - when I do the cabal steps from the readme I get:
```
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
[__0] trying: LambdaHack-0.10.2.0 (user goal)
[__1] trying: int-cast-0.2.0.0 (dependency of LambdaHack)
[__2] next goal: base (dependency of LambdaHack)
[__2] rejecting: base-4.15.0.0/installed-4.15.0.0 (conflict: int-cast =>
base>=4.7 && <4.15)
[__2] skipping: base-4.15.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=4.7 && <4.15' from
'int-cast')
[__2] rejecting: base-4.14.1.0, base-4.14.0.0, base-4.13.0.0, base-4.12.0.0,
base-4.11.1.0, base-4.11.0.0, base-4.10.1.0, base-4.10.0.0, base-4.9.1.0,
base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0, base-4.7.0.2,
base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0, base-4.5.1.0,
base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0, base-4.3.0.0,
base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0, base-4.0.0.0,
base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable package requires
installed instance)
[__2] fail (backjumping, conflict set: LambdaHack, base, int-cast)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: LambdaHack, base, int-cast
```
I _was_ able to get it building with stack after adding 
```
- int-cast-0.2.0.0
- splitmix-0.1.0.3
```
but then `stack exec LambdaHack-exe` isn't finding an executable - since this is intended as a library I guess I need another step to make the actual sample game?
And to complicate matters I'm on windows. (Afaik I've set up sdl2 ok - it works with a different project.)
Can you help?

**Comment by Mikolaj** [comment]
Welcome! It'd be my pleasure to answer any questions, here or on discord, wherever you please.

I guess, with cabal, you are using a very new GHC, which the int-cast package has not been revised for yet. I think running cabal with `--allow-newer` should fix the issue, just as I do in CI:  https://github.com/LambdaHack/LambdaHack/blob/master/.travis.yml#L385

Independently, I'd like stack to work for LambdaHack, so let's try. Does `stack exec LambdaHack` work for you? `LambdaHack` is the name of the exe of the sample game: https://github.com/LambdaHack/LambdaHack/blob/master/LambdaHack.cabal#L438

**Comment by JamieFristrom** [comment]
`stack exec LambdaHack` got further! - it ran and then immediately popped out again with no messaging. That's a common problem with SDL2 and Windows I think; I've seen it on another game as well. The version of SDL2 I'm using takes over stdout & stderr so I can't see my error messages.

**Comment by JamieFristrom** [comment]
`cabal run LambdaHack --allow-newer` made progress on Windows, but then - 
```
Failed to build base-compat-0.11.2. The failure occurred during the configure
step.
Build log (
C:\Users\jdfri\AppData\Roaming\cabal\logs\ghc-9.0.1\base-compat-0.11.2-b4ab9941863390b7bbf18eb1545c6d3a5554bd09.log
):
Configuring library for base-compat-0.11.2..
C:\Users\jdfri\AppData\Local\Temp\ghc7362.o.tmp: renameFile:renamePath:MoveFileEx "\\\\?\\C:\\Users\\jdfri\\AppData\\Local\\Temp\\ghc7362.o.tmp" Just "\\\\?\\C:\\Users\\jdfri\\AppData\\Local\\Temp\\ghc7362.o": does not exist (The system cannot find the file specified.)

Failed to build base-orphans-0.8.4. The failure occurred during the configure
step.
Build log (
C:\Users\jdfri\AppData\Roaming\cabal\logs\ghc-9.0.1\base-orphans-0.8.4-b6f0cf0d1b062ee5dc515ee37eea7adc3c726815.log
):
Configuring library for base-orphans-0.8.4..
C:\Users\jdfri\AppData\Local\Temp\ghc7363.o.tmp: renameFile:renamePath:MoveFileEx "\\\\?\\C:\\Users\\jdfri\\AppData\\Local\\Temp\\ghc7363.o.tmp" Just "\\\\?\\C:\\Users\\jdfri\\AppData\\Local\\Temp\\ghc7363.o": does not exist (The system cannot find the file specified.)
```
I also tried building on Windows Subsystem Linux (1) Ubuntu 18.02 ->

**Comment by JamieFristrom** [comment]
Took a stab at building it with Windows Subsystem Linux (1) & Ubuntu 18 - there when I do `cabal run LambdaHack` I get 
```
[4 of 8] Compiling Utils            ( app/Utils.hs, dist/build/HetrisV2-exe/HetrisV2-exe-tmp/Utils.o )

app/Utils.hs:43:11: error:
    • Variable not in scope: (<>) :: T.Text -> [Char] -> t4
    • Perhaps you meant one of these:
        ‘<’ (imported from Prelude), ‘<$>’ (imported from Prelude),
        ‘*>’ (imported from Prelude)
```

**Comment by JamieFristrom** [comment]
I tried the Cabal method under WSL (1) with Ubuntu 18, ended up here - 
```
jafristr@POLARIS2:/mnt/c/mydev/LambdaHack$ cabal build .
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
cabal: LambdaHack.cabal:377: stray 'else' with no preceding 'if'
jafristr@POLARIS2:/mnt/c/mydev/LambdaHack$ cabal install cbal-plan
cabal: There is no package named 'cbal-plan'.
You may need to run 'cabal update' to get the latest list of available
packages.
jafristr@POLARIS2:/mnt/c/mydev/LambdaHack$ cabal install cabal-plan
Resolving dependencies...
All the requested packages are already installed:
cabal-plan-0.1.1.0
Use --reinstall if you want to reinstall anyway.
jafristr@POLARIS2:/mnt/c/mydev/LambdaHack$ cabal build .
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
cabal: LambdaHack.cabal:377: stray 'else' with no preceding 'if'
jafristr@POLARIS2:/mnt/c/mydev/LambdaHack$ cabal install cabal-plan --reinstall
Resolving dependencies...
In order, the following will be installed:
cabal-plan-0.1.1.0 (reinstall) (changes: ansi-terminal-0.6.3.1 added, mtl-2.2.2 added)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Configuring cabal-plan-0.1.1.0...
Building cabal-plan-0.1.1.0...
Installed cabal-plan-0.1.1.0
jafristr@POLARIS2:/mnt/c/mydev/LambdaHack$ cabal build .
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
cabal: LambdaHack.cabal:377: stray 'else' with no preceding 'if'
```

**Comment by Mikolaj** [comment]
> `stack exec LambdaHack` got further! - it ran and then immediately popped out again with no messaging. That's a common problem with SDL2 and Windows I think; I've seen it on another game as well. The version of SDL2 I'm using takes over stdout & stderr so I can't see my error messages.

I'd very much like to learn what the messages are --- I do intercept stdout and stderr if the terminal doesn't look legit

https://github.com/LambdaHack/LambdaHack/blob/master/GameDefinition/Main.hs#L47

and save them as files `stdout.txt` and `stderr.txt` in `C:\Users\<username>\AppData\Roaming\LambdaHack\` or somewhere similar.

If everything else fails, building similarly as I do in Windows CI should be possible (it uses `pacman` to install SDL2, SDL2_TTF, freetype and a lot of other libraries): 

https://github.com/LambdaHack/LambdaHack/blob/master/appveyor.yml#L44

**Comment by Mikolaj** [comment]
> I tried the Cabal method under WSL (1) with Ubuntu 18, ended up here -

This looks like too old cabal. Can you do `cabal --version`? I run my Linux CIs with cabal 3.4, but probably 3.2 and 3.0 should work too. Only Ubuntu 20.10 and later have cabal 3.0 and later. Of course, you can install a new cabal yourself in various ways, e.g., `cabal update; cabal install Cabal cabal-install`.

**Comment by Mikolaj** [comment]
> `cabal run LambdaHack --allow-newer` made progress on Windows, but then -

This is strange, because my CI on Linux builds fine with GHC 9.0.1 (and `--allow-newer`). Perhaps downgrade to GHC 10.*, which is more stable and then you don't need `--allow-newer` either?

**Comment by JamieFristrom** [comment]
I'm not seeing a stderr.txt or stdout.txt anywhere on my drive - I suspect the program is exiting before it gets to `main` if that's possible. The same thing is happening with HetrisV2; I'm sure it's something to do with SDL. Is there an alternative to SDL on Windows that LambdaHack will work with?

**Comment by Mikolaj** [comment]
There are alternatives, but SDL is by far the best. Did you install all the libraries listed here:   

https://github.com/LambdaHack/LambdaHack/blob/master/appveyor.yml#L54

e.g., by using the `pacman` command? The program will not work without any of those (and some are needed also with the other, non-SDL, frontends).

**Comment by Mikolaj** [comment]
Actually, you can probably take all the libraries from the binary package of LambdaHack and only copy the executable you compiled to the directory with the libraries --- not comfortable for development, but enough to test if the problems is missing dlls.

**Comment by JamieFristrom** [comment]
Where is the binary package? I'm having trouble finding it

**Comment by Mikolaj** [comment]
E.g., https://github.com/LambdaHack/LambdaHack/releases/latest

**Comment by JamieFristrom** [comment]
Oh I just didn't scroll down far enough :/
