### ISSUE TITLE
Split the long Content.ModeKind texts into lines

### ISSUE THREAD

**Issue by Mikolaj** [LambdaHack/LambdaHack#283]
both in LambdaHack and Allure. Currently the lines are divided by `\n` characters, but they are more readable presented as at

https://github.com/AllureOfTheStars/Allure/blob/3315a7195e27ed28a735841c61ee1f412ce99002/GameDefinition/Content/ModeKind.hs#L111

so this should be extended to each text in this file and its LambdaHack counterpart.

This is as easy issue as fixing typos, but improves readability and even automatic spell-checking a lot.

**Comment by kayvank** [comment]
@Mikolaj  was this implemented? I'd like to start contributing and am looking for my first issue.  Any suggestion is appreciated.

**Comment by Mikolaj** [comment]
@kayvank: hi! No, it was only implemented in a few texts. Let me know if I can guide you in setting up a fork with a proper `cabal.project.local` (as in README), creating a PR, etc. Matrix or Discord is probably the best place to chat about such things, but tickets are fine, too, especially about specific ticket-related topics.

**Comment by Mikolaj** [comment]
Done in LambdaHack. Only the Allure part remains now.

**Comment by kayvank** [comment]
@Mikolaj  Here is the [PR-117](https://github.com/AllureOfTheStars/Allure/pull/117) for Allure related work.

**Comment by Mikolaj** [comment]
Fixed in https://github.com/AllureOfTheStars/Allure/pull/117. Closing
