### ISSUE TITLE
Default config file copied only partially

### ISSUE THREAD

**Issue by Soupstraw** [LambdaHack/LambdaHack#284]
When I launch the game for the first time, it starts normally. When I close the game and open it again, I get the following error:
```
LambdaHack: Error when parsing configuration file. Please fix config.ui.ini or remove it altogether. The details:
Internal failure occurred and the following is to blame:
  Ini.parse sUser
  IniParserError
  "\"ini\" (line 39, column 18):\nunexpected end of input\nexpecting lf new-line"
CallStack (from HasCallStack):
  error, called at engine-src/Game/LambdaHack/Client/UI/UIOptionsParse.hs:37:19 in LambdaHack-0.11.0.0-inplace:Game.LambdaHack.Client.UI.UIOptionsParse
```
When I delete the config file in the `.LambdaHack` directory, the game again starts normally.

Looking at the generated config file in the `.LambdaHack` directory, it seems that it ends abruptly at a spot, where an accented `é` is supposed to appear in the template config file:
```
[hero_names]
HeroName_0 = ("Haskell Alvin", "he")
HeroName_1 = ("Alonzo Barkley", "he")
HeroName_2 = ("In
```

This bug happened on commit `57007a4` and also on the latest release versions.

**Comment by Mikolaj** [comment]
Thank you for the investigation. Indeed, this looks like some UTF mismatch. I've never seen it before. I've changed the file writing code to a locale-aware version, so perhaps it now works fine (CI finished building the fixed version).

**Comment by Mikolaj** [comment]
Actually, I don't think this will work. Could you paste the output of `locale` on your system? Perhaps I should detect if it's funny and then enforce something sane.

**Comment by Soupstraw** [comment]
Seems like my `LOCALE` was not configured properly on this machine. I changed it from "C" to "en_US.UTF-8" and then everything worked fine.

**Comment by Mikolaj** [comment]
Thank you. I'm no longer hiding any such exceptions and also overwriting too primitive locales twice over, so I hope this won't be a problem any more. Pushed, CI passed.
