### ISSUE TITLE
Deduplicate stub game arena elements in tests

### ISSUE THREAD

**Issue by Mikolaj** [LambdaHack/LambdaHack#286]
Perhaps some values from `UnitTestHelpers` can be replaced by those in `Game.LambdaHack.Common.Kind` and surely some in other tests can be replaced by those in `UnitTestHelpers`, because in some cases they are identical. 

If there is a benefit in the stub game arena elements being different in test files than in `UnitTestHelpers`, perhaps the extra ones should be moved to `UnitTestHelpers`, as well, and perhaps different blocks of tests in the same file could use different such elements, not just one.

**Comment by Mikolaj** [comment]
Example elements to deduplicate: `testLevel`, `stubItem`, `testItemBase`.

**Comment by kayvank** [comment]
@Mikolaj  I would like to take this task plz.

**Comment by Mikolaj** [comment]
Good choice. I don't have comments at this point, but please feel free to ask questions at any time.

**Comment by kayvank** [comment]
@Mikolaj 
> testItemBase
 is  used in [test/ItemDescriptionUnitTests.hs(https://github.com/LambdaHack/LambdaHack/blob/master/test/ItemDescriptionUnitTests.hs#L23)  only. Does it still need to be moved to UnitTestHelpers?

**Comment by Mikolaj** [comment]
Your call.

**Comment by kayvank** [comment]
I'll leave it there for now till we find a reuse for it down the line.
[PR-292](https://github.com/LambdaHack/LambdaHack/pull/292)  is ready for your review please. than you for your help.

**Comment by Mikolaj** [comment]
My pleasure. PR's can be referenced as in #292 as well.

**Comment by Mikolaj** [comment]
Closed by #292.
