### ISSUE TITLE
base-compat-0.13.1 - ambiguous occurence `unsnoc`

### ISSUE THREAD

**Issue by alaendle** [LambdaHack/LambdaHack#300]
Currently the compilation fails with base-compat-0.13. because another `unsnoc` was introduced.
See also https://hackage.haskell.org/package/base-compat-0.13.1/changelog
(Disabled on stackage nightly (fyi @Mikolaj))

**Comment by Mikolaj** [comment]
Thank you for the report. I will have a look in a week or two. BTW, LambdaHack (and transitively Allure)) will also require a bump of hsini to 0.5.2.2 for it to work, see https://github.com/LambdaHack/LambdaHack/issues/301.

**Comment by Mikolaj** [comment]
This should now be fixed by https://hackage.haskell.org/package/LambdaHack-0.11.0.1. I hope Allure can now be enabled back as well.

**Comment by Mikolaj** [comment]
@alaendle: do I need to do anything else to get LambdaHack back into Stackage nightly?

**Comment by alaendle** [comment]
The normal process is to create a PR to remove the constraint on stackage (or wait until one of the curators notices the new release (we have a tool that shows constraints of outdated versions)) - I've already created such a PR https://github.com/commercialhaskell/stackage/pull/7171 to accelerate things ;-) So if the PR is merged LambdaHack should appear on day later on nightly.

**Comment by Mikolaj** [comment]
Thank you so much, @alaendle.

**Comment by alaendle** [comment]
LambdHack is back - Allure will semi-automatically follow. https://www.stackage.org/diff/nightly-2023-11-10/nightly-2023-11-13 🥳
