### ISSUE TITLE
Create binaries for OSX

### ISSUE THREAD

**Issue by Mikolaj** [LambdaHack/LambdaHack#77]
[SOLVED] If somebody could create binaries for OSX, that would be much appreciated. Let me know in this issue or via email (mikolaj.konarski@funktory.com) where I can download the binaries from, and I will put them where others can easily find them, e.g., here:

https://github.com/LambdaHack/LambdaHack/releases
https://github.com/AllureOfTheStars/Allure/releases

For some time now one can create OSX binaries via travis, but I can't test them to determine, e.g., how many libraries to include with the binary vs what the OSX user should install on his own, so that doesn't solve the issue.

Edited: thanks to Pablo Reszczynski we can now create working Mac OS X binaries and their building is automated via a makefile stanza. What remains is putting the automated build on (travis?) CI and/or in Homebrew (#142).

**Comment by Mikolaj** [comment]
Here is a hint how to do that remotely on travis: https://github.com/haskell/ThreadScope/blob/master/.travis.yml

Still, access to a OSX machine, for debugging, would probably make it much less painful.

**Comment by Mikolaj** [comment]
See https://github.com/AllureOfTheStars/Allure/issues/79

**Comment by PabloReszczynski** [comment]
Would a simple cabal install suffice for this?

**Comment by PabloReszczynski** [comment]
Just noticed there is `build-binary-common` on the makefile, should I use that?

**Comment by Mikolaj** [comment]
Actually, if there is a common package format or installer for OS X, then the `make build-binary` you mention may come useful. Here is how I use it to create a Windows binary archive (and also an installer, later on): 

https://github.com/LambdaHack/LambdaHack/blob/master/appveyor.yml#L17

I copy by hand the SDL2 and other needed libraries. If there is a tool for OS X that automatically copies the needed libraries, that would be even better.

**Comment by Mikolaj** [comment]
@PabloReszczynski: Both LambdaHack and Allure releases v0.8.2.0 are now ready. Could we try to create OS X packages (or archives) before the release is published, in case we need to tweak anything in the repo (or in case we can add some script to Makefile to automate the task)?

**Comment by Mikolaj** [comment]
@PabloReszczynski: Well done with the binary archives! Please, try renaming the binaries to Allure_0.8.2.0_darwin-10.12.6-amd64.tar.gz, etc., or whatever exactly your OS/arch identification is, and uploading them, for now, to 

https://github.com/AllureOfTheStars/Allure/releases/tag/v0.8.0.0

and, respectively,

https://github.com/LambdaHack/LambdaHack/releases/tag/v0.8.0.0

because the 0.8.0.0 version is well advertised, but it lacks OS X binaries (and there are almost no user-visible changes in v0.8.2.0). If you can't upload, let me know and I will try to fix the github setup.

Could you also unpack your archives, enter their directories and try running

```
./Allure --dbgMsgSer --logPriority 4 --newGame 3 --noAnim --maxFps 100000 --benchmark --stopAfterFrames 2000 --automateAll --keepAutomated --gameMode battle --setDungeonRng 7 --setMainRng 7
```

and similarly for Lambdaahck? What are your outputs for each archive? That's a quick test that also lets us compare if it works the same on all architectures, if the optimization level is right, etc.

If it's not too much to ask, could you then issue pull requests for the Makefile on both repos that adds a target build-darwin-binary (and renames build-binary to build-ubuntu-binary)? Just copy-paste with the required changes. Remember about tabs instead of spaces, because Makefile is fussy about it. Let me know if I can assist you.

When it's all shaken up, I will skip v0.8.2.0 and release v0.8.3.0 to Hackage to mark the breakthrough (and I would include a couple of extra tweaks) and upload our new binaries to some other sites and then advertise it. I wonder if there are some special pages where game-starved OS X people come to download free games? We could upload it there as well. Or is it all iTunes these days?

**Comment by Mikolaj** [comment]
Or perhaps make it Allure_0.8.2.0_osx-10.12.6-amd64.tar.gz? I have no idea if ordinary players are aware that they own a Darwin. Or OSX? Or MacOsX? What is most understandable?

**Comment by PabloReszczynski** [comment]
## Test output for Allure:
```
./Allure --dbgMsgSer --logPriority 4 --newGame 3 --noAnim --maxFps 100000 --benchmark --stopAfterFrames 2000 --automateAll --keepAutomated --gameMode battle --setDungeonRng 7 --setMainRng 7
  1.     82 Spacefarers perished on level 5, killed 41, lost 4,
            difficulty 3, after 335 turns on 2018-06-23 17:46:25.
Game time: 5.358882s; frames: 1223. Average clips per second: 624.5705727425982. Average FPS: 228.21924423788394.
Session time: 8.592441s; frames: 2001. Average clips per second: 719.2368268807431. Average FPS: 232.8791085094445.
```
## Test output for LambdaHack
```
./LambdaHack --dbgMsgSer --logPriority 4 --newGame 3 --noAnim --maxFps 100000 --benchmark --stopAfterFrames 2000 --automateAll --keepAutomated --gameMode battle --setDungeonRng 7 --setMainRng 7
  1.   1315 Explorers slew all opposition, killed 69, lost 2,
            difficulty 3, after 428 turns on 2018-06-23 17:49:07.
Game time: 5.011076s; frames: 1558. Average clips per second: 852.7110744279272. Average FPS: 310.9112693561223.
Session time: 6.243039s; frames: 2002. Average clips per second: 851.5083759688191. Average FPS: 320.67715739081564.
```

**Comment by PabloReszczynski** [comment]
As for most understandable name I think macosx is best.
And about where do we get our games, normally I use [Homebrew](https://brew.sh/), so making it available there would be a plus.

**Comment by Mikolaj** [comment]
Our numbers match, so the OS doesn't affect, e.g., randomness, and threads are handled in a deterministic enough fashion that differences in scheduling don't manifest. Perfect. That also means debugging, given a game seed is possible across OSes. Also, your machine has a nice single core performance. :) I'm fine with you uploading these binaries to the v0.8.0.0 release. Let me know if it fails.

### Ubuntu output for Allure

```
dist/build/Allure/Allure --dbgMsgSer --logPriority 4 --newGame 3 --noAnim --maxFps 100000 --benchmark --stopAfterFrames 2000 --automateAll --keepAutomated --gameMode battle --setDungeonRng 7 --setMainRng 7
  1.     82 Spacefarers perished on level 5, killed 41, lost 4,
            difficulty 3, after 335 turns on 2018-06-24 00:06:18.
Game time: 9.876390476s; frames: 1223. Average clips per second: 338.8889906827131. Average FPS: 123.83066495517123.
Session time: 17.340515039s; frames: 2001. Average clips per second: 356.3907984336543. Average FPS: 115.39449638604243.
```

### Ubuntu output for LambdaHack

```
dist/build/LambdaHack/LambdaHack --dbgMsgSer --logPriority 4 --newGame 3 --noAnim --maxFps 100000 --benchmark --stopAfterFrames 2000 --automateAll --keepAutomated --gameMode battle --setDungeonRng 7 --setMainRng 7
  1.   1315 Explorers slew all opposition, killed 69, lost 2,
            difficulty 3, after 428 turns on 2018-06-23 23:58:33.
Game time: 8.953732856s; frames: 1558. Average clips per second: 477.23112457354733. Average FPS: 174.00563821333648.
Session time: 11.402314499s; frames: 2002. Average clips per second: 466.22113435532947. Average FPS: 175.57838806985885.
```

**Comment by Mikolaj** [comment]
@PabloReszczynski: I've commented directly on your PR. Looks good, thank you.

Re Homebrew, sounds reasonable. Would you create an issue about making the package/formula/whatever? On LambdaHack or on Allure issue tracker, whichever is handy for you. And if you'd like, at any point, to tackle it, you have my utmost trust. :)

**Comment by Mikolaj** [comment]
I succumbed to "just one more commit", so 0.8.3.0 is cut right now. Let me tag it to prevent further drift.

**Comment by Mikolaj** [comment]
I succumbed one last time and did the shameful thing and moved the tag. Won't happen again (probably).

**Comment by PabloReszczynski** [comment]
## MacOS output for Allure 0.8.3.0
```
./Allure --dbgMsgSer --logPriority 4 --newGame 3 --noAnim --maxFps 100000 --benchmark --stopAfterFrames 2000 --automateAll --keepAutomated --gameMode battle --setDungeonRng 7 --setMainRng 7
  1.   1302 Spacefarers slew all opposition, killed 83, lost 3,
            difficulty 3, after 823 turns on 2018-06-29 08:58:27.
Game time: 8.493132s; frames: 1891. Average clips per second: 968.3118077053318. Average FPS: 222.65048983107764.
Session time: 9.31504s; frames: 2000. Average clips per second: 951.9014411102905. Average FPS: 214.7065391023549.
```

## MacOS output for LambdaHack
```
./LambdaHack --dbgMsgSer --logPriority 4 --newGame 3 --noAnim --maxFps 100000 --benchmark --stopAfterFrames 2000 --automateAll --keepAutomated --gameMode battle --setDungeonRng 7 --setMainRng 7
  1.   1325 Explorers slew all opposition, killed 65, lost 0,
            difficulty 3, after 393 turns on 2018-06-29 09:00:37.
Game time: 3.565023s; frames: 799. Average clips per second: 1100.133154821161. Average FPS: 224.12197621165416.
  1.   1330 Explorers slew all opposition, killed 67, lost 0,
            difficulty 3, after 166 turns on 2018-06-29 09:00:39.
Game time: 1.629762s; frames: 921. Average clips per second: 1018.5536293029289. Average FPS: 565.1131883060226.
Session time: 5.7648s; frames: 2002. Average clips per second: 1039.9320011101859. Average FPS: 347.28004440743825.
```

**Comment by Mikolaj** [comment]
Thank you very much. Well done. We have the same outputs. I moved the tag for the last time and now it matches your binaries and I will cut mine from the same tag (which is very fortunate, I wanted these last moment changes in and now they are in).

**Comment by Mikolaj** [comment]
v0.8.3.0 is released! With Mac OS X binaries! Score!

**Comment by Mikolaj** [comment]
@PabloReszczynski: release v0.9 is imminent. Would you like to create OSX binaries using the current state of master branch of LambdaHack and of Allure? GHC 8.6.4 would be best and the invocation is the on you prepaired, namely 'make build-binary-macosx`. Cheers!

**Comment by Mikolaj** [comment]
I'm now offloading creating the OSX binaries to Homebrew. Get them via `brew install allureofthestars`.

@PabloReszczynski: thank you for your help and for initiating the homebrew effort.

Closing.
