### ISSUE TITLE
Port command-line argument handling to a better library

### ISSUE THREAD

**Issue by Mikolaj** [LambdaHack/LambdaHack#87]
This may be a good choice

http://hackage.haskell.org/package/optparse-applicative

used as in, e.g., 

https://github.com/hvr/uhttpc/blob/master/src-exe/uhttpc-bench.hs

and

https://github.com/edsko/ide-backend-client/blob/master/src/IdeSession/Client/CmdLine.hs

**Comment by Mikolaj** [comment]
But ideally, we'd merge commandline and config arguments, as in https://github.com/zerobuzz/configifier

**Comment by vrom911** [comment]
@Mikolaj, I can implement cli argument handling with `optparse-applicative` is that's still the case.

**Comment by Mikolaj** [comment]
@vrom911: yay, that would be great. I was tempted by https://github.com/zerobuzz/configifier, but it seems to be forever marked as experimental, so using it could prove quite a challenge and involve contributing to it as well (which, BTW, should be fun, but a lot more work than an ad-hoc solution, I'm sure). Already optparse-applicative is quite an overkill for our modest needs, but it's pretty and actively supported by many people, so I'd go for it, unless you prefer https://hackage.haskell.org/package/cmdargs, which is another serious contender.
 
The rewrite should shrink the commandline handling code a lot and make it easier to modify, so when the time comes to unify/systematize .ini config, commandline and on-screen config, it will be easier to proceed with. Also, arbitrarily complex commands will be easy to add, if we ever need to.

**Comment by Mikolaj** [comment]
The original options were contrived due to primitive tooling so after we merge the optparse-applicative PR, we can make the options more user-friendly using the new toolset. Then, based on the experience from using it, we can polish any rough edges on our setup for the toolset itself. Some TODO items spotted so far:

- Descriptions should be capitalized to match the convention exemplified in the --help description.
- The help text mentions `config.rules.ini`, which is no longer the correct name. Perhaps we should take it from Content.RuleKind to make sure it doesn't get out of sync again.
- In descriptions like "exit game session after around n seconds" either unify the metavariable name and `n` or remove the `n` (we'd better decide which of the two styles to use and stick to it; I like unifying the two better, because otherwise the metavariables are mostly unused; but if so, no more INT, but K, N, etc. instead).

**Comment by vrom911** [comment]
@Mikolaj good points! 
Also I have some addition to the list: I've noticed in the description some conditions like `(needs --knowMap)` but no check was provided. I guess this needs to be improved too. But probably this could be identified as a separate problem..

**Comment by Mikolaj** [comment]
I've used the new machinery to improve the user experience and also tied all the loose ends. Thank you again. Closing.
