### ISSUE TITLE
Add/improve item description texts

### ISSUE THREAD

**Issue by Mikolaj** [LambdaHack/LambdaHack#90]
The descriptions are stored in field `idesc` of the `ItemKind` records in directory `GameDefinition/Content/`, in all `ItemKind*.hs` files except `ItemKindActor.hs` and `ItemKindOrgan.hs` (these two concern actors, not items and related entities, and there is a separate github issue for them). The descriptions are expected to be rather concise and, more or less, justify and colour the stats.

The ordinary item descriptions are displayed in inventory menus and some of the others may be visible in the actor organs menu or when the cursor is on a projectile in targeting mode. All the descriptions are also displayed in the info `~` menu, where everything ever seen by the player is available for perusing.

Edit: the descriptions are assumed to be licensed under BSD3. This should spare all of us us any legal headaches when moving content between various free software games based on LambdaHack.

**Comment by Mikolaj** [comment]
The rudimentary `~` menu is already implemented on branch `master`. To have full information about all item created during a game, start it with the following debug options:

```
LambdaHack --dbgMsgSer --dumpInitRngs --newGame 2 --gameMode exploration --knowMap --knowEvents --knowItems
```

**Comment by Mikolaj** [comment]
Some remarks about the theme and mood of LambdaHack the game (better late than never): https://github.com/LambdaHack/LambdaHack/wiki/Sample-dungeon-crawler

**Comment by Mikolaj** [comment]
The descriptions waiting to be written can be discovered with `git grep "desc .* = \"\""`. Improvements to existing descriptions are also welcome.

**Comment by Mikolaj** [comment]
@Peritract: If you'd like, at your leisure, to give all item descriptions a fresh look, it should be much more comfortable now. I've just added all kinds of amenities for content creators:
* the `~` menu with many screens
* easy perusal of descriptions: when you enter an item description in `~` menu, up and down arrows show descriptions of neighbouring items
* displaying items embedded in a tile when the crosshair is positioned over the tile
* a `make expose-lore` shorthand for peeking at all items created at game start (to see more items, in particular blasts and temporary conditions, you need to play the game a bit, e.g, with `a` command from the Main Menu)
* I also tweaked and rebalanced item content
* I extended https://github.com/LambdaHack/LambdaHack/wiki/Sample-dungeon-crawler

Happy New Year! :)

**Comment by Mikolaj** [comment]
Edit: I've just completely overhauled https://github.com/LambdaHack/LambdaHack/wiki/Sample-dungeon-crawler

**Comment by Mikolaj** [comment]
@tuturto: the changes mentioned above also make this a good moment to port your space-privateers content to the new format. I expect, for some time now, I won't be making any more changes that make merging content files difficult. The Early Dev form thread at

http://forums.roguetemple.com/index.php?topic=5454.0

may be a good place to discuss porting issues, so that others can benefit as well. Happy New Year! :)

**Comment by Mikolaj** [comment]
After a flurry of extensive changes in the last several days, the content API and the content itself of LambdaHack and of Allure are again semi-stable. I don't plan to change them before 0.8.0.0 is released which won't be very soon, because there were big changes to the code and the balance, so it needs a lot of testing and bugfixing now. Anyway, now is again a good time for anyone interested to hack on the content. :)

BTW, for people on Windows, the fresh installers of development versions are always available from https://ci.appveyor.com/project/Mikolaj/lambdahack/build/artifacts and https://ci.appveyor.com/project/Mikolaj/allure/build/artifacts (or from similar pages for branches, PRs or when master is just building). If anybody with Windows 10 (or whatever is the latest version) could confirm it works for him, I'd be grateful.

**Comment by Mikolaj** [comment]
@tuturto @Peritract: I've just finished another major overhaul of content format and content itself, including examples of conveying backstory, and I hope these bits will now remain pretty stable for a few months. Just saying. :)

See https://www.reddit.com/r/roguelikedev/comments/9byp9e/sharing_saturday_222/e56q56a

**Comment by Peritract** [comment]
Are you looking for descriptions for the potions as well as the other item types?

**Comment by Mikolaj** [comment]
@Peritract: yes, definitely for the potions (and any items in LambdaHack and in Allure) that have a commented out `idesc    = ""` in their definition. For others it may be quite hard to design descriptions that would add to the mood and suspension of disbelief rather than strain them by trying too hard or by turning attention to their purely enable-interesting-gameplay-mechanics character. I mean especially the potions/flasks/scrolls that are rather generic (one effect only, no `ELabel`). The ones that combine some stuff and suggest some common/leading theme, say "potion of fear" are more likely to benefit from descriptions. BTW, any brainstorming about adding flavourful names (`ELabel`) and/or merging or extending the consumables are welcome.

BTW, the bits of backstory I was tacking about are mostly in Allure. Ideas welcome about how to best convey the backstory, characters, plot, etc.

**Comment by Mikolaj** [comment]
Most of the needed descriptions have been masterfully composed by @Peritract in #150, so only a few remain until the issue can be closed, most in `ItemKindBlast.hs` (flying explosion blast particle descriptions) and `ItemKindBlast.hs` (embedded items, that is, the active aspect of terrain tiles).

**Comment by Mikolaj** [comment]
Now that all items except embedded items and organs have proper descriptions, closing in favour of #158. Thank you again.
