### ISSUE TITLE
Question about browser UI extension for LambdaHack

### ISSUE THREAD

**Issue by reyman** [LambdaHack/LambdaHack#91]
Hi,

I'm interested to learn haskell in the future (i currently develop in Scala), and IMHO roguelike is always a good  start to learn a new langage :)

I'm interested to know about front end capacities of LambdaHack, do you consider an UI with JS using  FRP library / GHCJS and perhaps React (http://iankduncan.com/posts/2014-12-16-react-js-with-ghcjs.html) is a possible and feasible way to extend/play with LambdaHack ? 

Best regards,
SR

**Comment by Mikolaj** [comment]
> roguelike is always a good start to learn a new langage :)

Absolutely confirmed. ;)

> I'm interested to know about front end capacities of LambdaHack

Currently the frontend is very isolated from the clients (and the server, obviously). It just uses a two-way channel to communicate with a client, with some extra hacks. After v0.5 I intend to clean it up and simplify a bit more (e.g., stop cheating and really have one frontend per UI client). Also, extend the frontend-client protocol and get rid of the hacks as soon as the protocol is rich enough. Being isolated, the frontend can be modified and experimented with quite easily.

> do you consider an UI with JS using FRP library / GHCJS and perhaps React (http://iankduncan.com/posts/2014-12-16-react-js-with-ghcjs.html) is a possible and feasible way to extend/play with LambdaHack ? 

By all means. There are two related issues: https://github.com/LambdaHack/LambdaHack/issues/80 https://github.com/LambdaHack/LambdaHack/issues/56.

I'm thinking, perhaps only the frontend should be implemented in FRP style. Much less likely the (fat) clients and the server. But if only tiny outer layers of clients and/or server were driven by FRP and the rest of their code assumed that game-time is frozen, that could still fit the current code-base and avoid introducing too much conceptual and computational overhead throughout the code. In some bits of the server I'm indeed struggling with time dependencies and expressing them by just the order of monadic instructions. If FRP could be used cheaply there, that could be very beneficial. However, for a start, I'd touch only the frontend. BTW, if you look at the code that links the server, the clients and the frontend, please use the 'mikolaj' branch --- I've just simplified it visually a lot and added some haddocks. Have fun. :)

**Comment by reyman** [comment]
Thanks for your comment :)

What is the best IDE in your opinion to start programming in Haskell ?

**Comment by Mikolaj** [comment]
Emacs, of course (https://github.com/haskell/haskell-mode). ;)

That's a common question on haskell-cafe, but I don't know what the current answers are, e.g., how usable Eclipse is for Haskell right now.

**Comment by Mikolaj** [comment]
See interesting discussion at http://www.reddit.com/r/haskellgamedev/comments/31fi0f/lambdahack_haskell_roguelike_engine_stabilizes/cqdo2jk

**Comment by Mikolaj** [comment]
A pre-release of a contrived Web frontend to LambdaHack is at https://lambdahack.github.io/

**Comment by Mikolaj** [comment]
It's now released. Please give it a try and post feedback. :)

**Comment by Mikolaj** [comment]
Another release is out: 

https://twitter.com/AllureRoguelike/status/942854380025466880

Please post feedback on

http://forums.roguetemple.com/index.php?topic=5454.0

or in some other place. Thank you! Closing the issue.
